let monkeys = [
  {
    name: Emma,
    species: redbuttmonkey,
    price: $800,
    avaliable: yes,
    age: 1,
    gender: female,
    smart: sorta,
  },
  {
    name: Daquavian,
    species: Snubnosedmonkey,
    price: $500,
    avaliable: yes,
    age: 0.5,
    gender: male,
    smart: no,
  },
  {
    name: Demarcus,
    species: baboon,
    price: $1,
    avaliable: yes,
    age: 2,
    gender: male,
    smart: no,
  },
  {
    name: Tyrone,
    species: Spidermonkey,
    price: $1000,
    avaliable: yes,
    age: 3,
    gender: male,
    smart: no,
  },
  {
    name: Jamal,
    species: Howlermonkey,
    price: $900,
    avaliable: yes,
    age: 1.5,
    gender: male,
    smart: no,
  },
  {
    name: Gertrude,
    species: redbuttmonkey,
    price: $5,
    avaliable: no,
    age: 0.2,
    gender: female,
    smart: no,
  },
  {
    name: Bertrude,
    species: orangutan,
    price: $200,
    avaliable: no,
    age: 1,
    gender: female,
    smart: yes,
  },
  {
    name: Bob,
    species: gibbon,
    price: $2000,
    avaliable: yes,
    age: 2,
    gender: male,
    smart: no,
  },
  {
    name: Bobby,
    species: chimpanzee,
    price: $1500,
    avaliable: yes,
    age: 1.5,
    gender: male,
    smart: no,
  },
  {
    name: Tammy,
    species: tamarin,
    price: $350,
    avaliable: yes,
    age: 1,
    gender: female,
    smart: yes,
  },
  {
    name: Tommy,
    species: gorilla,
    price: $400,
    avaliable: yes,
    age: 0.3,
    gender: male,
    smart: no,
  },
  {
    name: Johnny,
    species: gorilla,
    price: $2500,
    avaliable: yes,
    age: 5,
    gender: male,
    smart: yes,
  },
  {
    name: SIUUUU,
    species: proboscismonkey,
    price: $1000000,
    avaliable: yes,
    age: 16,
    gender: female,
    smart: no,
  },
];
export { monkeys };
