let monkeys = [
  {
    name: "Emma",
    species: "redbuttmonkey",
    price: "$800",
    available: true,
    age: 1,
    gender: "female",
    smart: "sorta",
  },
  {
    name: "Daquavian",
    species: "Snubnosedmonkey",
    price: "$500",
    available: true,
    age: 0.5,
    gender: "male",
    smart: "no",
  },
  {
    name: "Demarcus",
    species: "baboon",
    price: "$1",
    available: true,
    age: 2,
    gender: "male",
    smart: "no",
  },
  {
    name: "Tyrone",
    species: "Spidermonkey",
    price: "$1000",
    available: true,
    age: 3,
    gender: "male",
    smart: "no",
  },
  {
    name: "Jamal",
    species: "Howlermonkey",
    price: "$900",
    available: true,
    age: 1.5,
    gender: "male",
    smart: "no",
  },
  {
    name: "Gertrude",
    species: "redbuttmonkey",
    price: "$5",
    available: false,
    age: 0.2,
    gender: "female",
    smart: "no",
  },
  {
    name: "Bertrude",
    species: "orangutan",
    price: "$200",
    available: false,
    age: 1,
    gender: "female",
    smart: "yes",
  },
  {
    name: "Bob",
    species: "gibbon",
    price: "$2000",
    available: true,
    age: 2,
    gender: "male",
    smart: "no",
  },
  {
    name: "Bobby",
    species: "chimpanzee",
    price: "$1500",
    available: true,
    age: 1.5,
    gender: "male",
    smart: "no",
  },
  {
    name: "Tammy",
    species: "tamarin",
    price: "$350",
    available: true,
    age: 1,
    gender: "female",
    smart: "yes",
  },
  {
    name: "Tommy",
    species: "gorilla",
    price: "$400",
    available: true,
    age: 0.3,
    gender: "male",
    smart: "no",
  },
  {
    name: "Johnny",
    species: "gorilla",
    price: "$2500",
    available: true,
    age: 5,
    gender: "male",
    smart: "yes",
  },
  {
    name: "SIUUUU",
    species: "proboscismonkey",
    price: "$1000000",
    available: true,
    age: 16,
    gender: "female",
    smart: "no",
  },
  {
    name: "Chaquille",
    species: "gorilla",
    price: "$50",
    available: true,
    age: 35,
    gender: "male",
    smart: "no",
  },
  {
    name: "Pablo",
    species: "capuchin",
    price: "$2",
    available: true,
    age: 49,
    gender: "male",
    smart: "no",
  },
];
export { monkeys };
